using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;

namespace MineSweeper
{
    class animations
    {
        public static void boom()
        {
            Console.Clear();
            Console.WriteLine("\n\n\n");
            Console.WriteLine("\t                                                                                                    ");
            Console.WriteLine("\t                                                                                                   ");
            Console.WriteLine("\t                                                                                                    ");
            Console.WriteLine("\t                                                                                                     ");
            Console.WriteLine("\t                                                                                                    ");
            Console.WriteLine("\t                                                                                               ");
            Console.WriteLine("\t                        BBBBB     OOOO    OOOO   MM        MM                                ");
            Console.WriteLine("\t                        BB  BB   OO  OO  OO  OO  MMM      MMM                                ");
            Console.WriteLine("\t                        BB   BB  OO  OO  OO  OO  MMMM    MMMM                                ");
            Console.WriteLine("\t                        BBBBBB   OO  OO  OO  OO  MMMMM  MMMMM                                ");
            Console.WriteLine("\t                        BB   BB  OO  OO  OO  OO  MM  MMMM  MM                                ");
            Console.WriteLine("\t                        BB  BB   OO  OO  OO  OO  MM   MM   MM                                 ");
            Console.WriteLine("\t                        BBBBB     OOOO    OOOO   MM        MM                                 ");
            Console.WriteLine("\t                                                                                                ");
            Console.WriteLine("\t                                                                                                   ");
            Console.WriteLine("\t                                                                                                    ");
            Console.WriteLine("\t                                                                                                   ");
            Console.WriteLine("\t                                                                                                   ");
            Console.WriteLine("\t                                                                                                   ");
            Console.WriteLine("\t                                                                                                  ");
            Thread.Sleep(500);

            Console.Clear();
            Console.WriteLine("\n\n\n");
            Console.WriteLine("\t                                          \\  |                                                     ");
            Console.WriteLine("\t                             \\  |   \\  |  |  |  |  |  /                                         ");
            Console.WriteLine("\t                       \\_ \\ |   \\  |  |   \\ | /   |  |  /  |  / _                              ");
            Console.WriteLine("\t                      \\_ \\ \\ \\  |   \\  \\  | | |  /  /   |  / / /  _/                           ");
            Console.WriteLine("\t             __   \\__  \\ \\ \\ \\  \\  |  |  | | |  |  |  /  / / /  / __/___                      ");
            Console.WriteLine("\t              \\___  \\_                                         _/  /     _____               ");
            Console.WriteLine("\t          _____   \\___  BBBBB     OOOO    OOOO   MM        MM  ___/     /                    ");
            Console.WriteLine("\t               \\______  BB  BB   OO  OO  OO  OO  MMM      MMM  ________/      /              ");
            Console.WriteLine("\t           ___________  BB   BB  OO  OO  OO  OO  MMMM    MMMM  ______________/               ");
            Console.WriteLine("\t             ---------  BBBBBB   OO  OO  OO  OO  MMMMM  MMMMM  -----------------             ");
            Console.WriteLine("\t           ___________  BB   BB  OO  OO  OO  OO  MM  MMMM  MM  _______________               ");
            Console.WriteLine("\t                ______  BB  BB   OO  OO  OO  OO  MM   MM   MM  _________      \\              ");
            Console.WriteLine("\t          _____/   ___  BBBBB     OOOO    OOOO   MM        MM  ____     \\_____               ");
            Console.WriteLine("\t               ___/  _                                        \\    \\____                      ");
            Console.WriteLine("\t           ___/   __/ / / / /  /  |  |  | | |  |  | \\   \\ \\ \\  \\___                           ");
            Console.WriteLine("\t               __/  _/ / / /  |   /  /  | | |   \\  \\ |   \\ \\ \\__                               ");
            Console.WriteLine("\t             _/   _/  / / |  /   |  |   / | \\    |  | \\  |  \\                                   ");
            Console.WriteLine("\t                _/   / | /  |   /   |  |  |  |   |  \\  | \\                                       ");
            Console.WriteLine("\t                      /    /   |    /  |  |  |   \\   |                                            ");
            Console.WriteLine("\t                                       /  |  |                                                    ");
            Thread.Sleep(500);

            Console.Clear();
            Console.WriteLine("\n\n\n");
            Console.WriteLine("\t                        \\  \\   \\  |   \\  |  |  |  /   |  /  /                                  ");
            Console.WriteLine("\t         __     \\_  \\  \\  \\  |   \\  |  |  |  |  |  /   | /   /   /                           ");
            Console.WriteLine("\t    __     \\__    \\_ \\_ \\ |   \\  |  |   \\ | /   |  |  /  |  / _ / _/                         ");
            Console.WriteLine("\t      \\___    \\__   \\_ \\ \\ \\  |   \\  \\  | | |  /  /   |  / / /  _/  __/  _                   ");
            Console.WriteLine("\t          \\___   \\__  \\ \\ \\ \\  \\  |  |  | | |  |  |  /  / / /  / __/____/                    ");
            Console.WriteLine("\t    ___       \\___  \\_                                         _/  /     _________           ");
            Console.WriteLine("\t       \\_______   \\___  BBBBB     OOOO    OOOO   MM        MM  ___/     /      ____          ");
            Console.WriteLine("\t    ______     \\______  BB  BB   OO  OO  OO  OO  MMM      MMM  ________/      /              ");
            Console.WriteLine("\t          \\___________  BB   BB  OO  OO  OO  OO  MMMM    MMMM  ______________/               ");
            Console.WriteLine("\t    ------------------  BBBBBB   OO  OO  OO  OO  MMMMM  MMMMM  --------------------------    ");
            Console.WriteLine("\t           ___________  BB   BB  OO  OO  OO  OO  MM  MMMM  MM  _______________               ");
            Console.WriteLine("\t    ______/     ______  BB  BB   OO  OO  OO  OO  MM   MM   MM  _________      \\_________     ");
            Console.WriteLine("\t        _______/   ___  BBBBB     OOOO    OOOO   MM        MM  ____     \\________            ");
            Console.WriteLine("\t    ___/       ___/  _                                        \\    \\____         \\____       ");
            Console.WriteLine("\t           ___/   __/ / / / /  /  |  |  | | |  |  | \\   \\ \\ \\  \\___     \\____                ");
            Console.WriteLine("\t       ___/    __/  _/ / / /  |   /  /  | | |   \\  \\ |   \\ \\ \\__   \\___      \\_              ");
            Console.WriteLine("\t            __/   _/  / / |  /   |  |   / | \\    |  | \\  |  \\   \\__    \\___                   ");
            Console.WriteLine("\t         __/    _/   / | /  |   /   |  |  |  |   |  \\  | \\   \\     \\__                         ");
            Console.WriteLine("\t              _/    / / /  /   |    /  |  |  |   \\   |  \\ \\   \\                                ");
            Console.WriteLine("\t                     / |  |   /    |   /  |  |    |   \\  | \\                                    ");
            Thread.Sleep(500);

            Console.Clear();
            Console.WriteLine("\n\n\n");
            Console.WriteLine("\t     \\__      \\_  \\_  \\  \\   \\  |   \\  |  |  |  /   |  /  /   /   _/  _/     __/        ____ ");
            Console.WriteLine("\t _      \\__     \\_  \\  \\  \\  |   \\  |  |  |  |  |  /   | /   /   /  _/    __/      ____/     ");
            Console.WriteLine("\t  \\___     \\__    \\_ \\_ \\ |   \\  |  |   \\ | /   |  |  /  |  / _ / _/   __/    ____/          ");
            Console.WriteLine("\t      \\___    \\__   \\_ \\ \\ \\  |   \\  \\  | | |  /  /   |  / / /  _/  __/  ____/      ________ ");
            Console.WriteLine("\t          \\___   \\__  \\ \\ \\ \\  \\  |  |  | | |  |  |  /  / / /  / __/____/          /         ");
            Console.WriteLine("\t ______       \\___  \\_                                         _/  /     _________/          ");
            Console.WriteLine("\t       \\_______   \\___  BBBBB     OOOO    OOOO   MM        MM  ___/     /      _____________ ");
            Console.WriteLine("\t _________     \\______  BB  BB   OO  OO  OO  OO  MMM      MMM  ________/      /              ");
            Console.WriteLine("\t          \\___________  BB   BB  OO  OO  OO  OO  MMMM    MMMM  ______________/               ");
            Console.WriteLine("\t ---------------------  BBBBBB   OO  OO  OO  OO  MMMMM  MMMMM  ----------------------------- ");
            Console.WriteLine("\t           ___________  BB   BB  OO  OO  OO  OO  MM  MMMM  MM  _______________               ");
            Console.WriteLine("\t _________/     ______  BB  BB   OO  OO  OO  OO  MM   MM   MM  _________      \\_____________ ");
            Console.WriteLine("\t        _______/   ___  BBBBB     OOOO    OOOO   MM        MM  ____     \\________            ");
            Console.WriteLine("\t ______/       ___/  _                                        \\    \\____         \\__________ ");
            Console.WriteLine("\t           ___/   __/ / / / /  /  |  |  | | |  |  | \\   \\ \\ \\  \\___     \\____                ");
            Console.WriteLine("\t       ___/    __/  _/ / / /  |   /  /  | | |   \\  \\ |   \\ \\ \\__   \\___      \\____           ");
            Console.WriteLine("\t   ___/     __/   _/  / / |  /   |  |   / | \\    |  | \\  |  \\   \\__    \\___       \\____      ");
            Console.WriteLine("\t _/      __/    _/   / | /  |   /   |  |  |  |   |  \\  | \\   \\     \\__     \\___        \\____ ");
            Console.WriteLine("\t      __/     _/    / / /  /   |    /  |  |  |   \\   |  \\ \\   \\       \\__      \\___          ");
            Console.WriteLine("\t   __/      _/     / / |  |   /    |   /  |  |    |   \\  | \\   \\         \\         \\         ");
            Thread.Sleep(500);

        }
        public static void gameName()
        {
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine();
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("\n");
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("\n\n");
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("\n\n\n");
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("\n\n\n\n");
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine();
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("\n\n\n");
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("\n\n\n\n");
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine();
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(200);
            Console.Clear();            
        }
    }
}
