using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;

namespace MineSweeper
{
    class animations
    {
        public static void gameName()
        {
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Thread.Sleep(400);
            Console.Clear();

            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine();
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("\n");
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("\n\n");
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("\n\n\n");
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("\n\n\n\n");
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine();
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("\n\n\n");
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine("\n\n");
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("\n\n\n\n");
            Console.Write($"\t\t\t\t     MMM            MMM  IIIII  NNNNN      NNN  DDDDD\n");
            Console.Write($"\t\t\t\t     MMMM          MMMM  IIIII  NNNNNN     NNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMMMM        MMMMM  IIIII  NNNNNNN    NNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMMMMM      MMMMMM  IIIII  NNN NNNN   NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMM    MMMMMMM  IIIII  NNN  NNNN  NNN  DDD     DDD\n");
            Console.Write($"\t\t\t\t     MMMMMMMM  MMMMMMMM  IIIII  NNN   NNNN NNN  DDD    DDD\n");
            Console.Write($"\t\t\t\t     MMM MMMMMMMMMM MMM  IIIII  NNN    NNNNNNN  DDD  DDDD\n");
            Console.Write($"\t\t\t\t     MMM   MMMMMM   MMM  IIIII  NNN     NNNNNN  DDDDDDD\n");
            Console.Write($"\t\t\t\t     MMM     MM     MMM  IIIII  NNN      NNNNN  DDDDD\n");
            Console.WriteLine();
            Console.Write($"        SSSSSSSS        CCCCCCCC     HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPP     EEEEEEEEEE  RRRRRRRR   \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWW        WWW  EEEEEEEEEE  PPPPPPPPPP   EEEEEEEEEE  RRRRRRRRRR \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWW        WWW  EEE         PPP    PPPP  EEE         RRR    RRRR\n");
            Console.Write($"     SSSSSSSS        CCC             HHHHHHHHHHH  WWW   WW   WWW  EEEEEE      PPP    PPPP  EEEEEE      RRR    RRRR\n");
            Console.Write($"       SSSSSSSSSS    CCC             HHHHHHHHHHH  WWW  WWWW  WWW  EEEEEE      PPPPPPPPPP   EEEEEE      RRRRRRRRRR \n");
            Console.Write($"            SSSSSSS  CCC             HHHHHHHHHHH  WWW WWWWWW WWW  EEE         PPPPPPPP     EEE         RRR  RRR   \n");
            Console.Write($"     SSSS      SSSS  CCCC      CCCC  HHH     HHH  WWWWWW  WWWWWW  EEE         PPP          EEE         RRR   RRR  \n");
            Console.Write($"      SSSSSSSSSSSS    CCCCCCCCCCCC   HHH     HHH  WWWWW    WWWWW  EEEEEEEEEE  PPP          EEEEEEEEEE  RRR    RRR \n");
            Console.Write($"         SSSSSSS        CCCCCCCC     HHH     HHH   WWW      WWW   EEEEEEEEEE  PPP          EEEEEEEEEE  RRR     RRR\n");
            Thread.Sleep(200);
            Console.Clear();            
        }
    }
}
